// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5RSlJsgGECnkGl3jd7ryTyZpfZ8Sv20g',
    appId: '1:1047298210999:web:d6ce4440626865c0e1e132',
    messagingSenderId: '1047298210999',
    projectId: 'kollekt-1466e',
    authDomain: 'kollekt-1466e.firebaseapp.com',
    storageBucket: 'kollekt-1466e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTLtyrU_SXxpeW4uZcq8h-jC3r1lNoAhU',
    appId: '1:1047298210999:android:1333a81a21629b9fe1e132',
    messagingSenderId: '1047298210999',
    projectId: 'kollekt-1466e',
    storageBucket: 'kollekt-1466e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTAIEp3Db_45MGk6B6MySl6ss3VMyGKlo',
    appId: '1:1047298210999:ios:7c6e93b7d8e87551e1e132',
    messagingSenderId: '1047298210999',
    projectId: 'kollekt-1466e',
    storageBucket: 'kollekt-1466e.firebasestorage.app',
    iosBundleId: 'com.sentinels.kollekt.kollekt',
  );
}
